babyday/views/event_log.py
import functools
from typing import List

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
import babyday.service.person_service as person_service
import babyday.service.eventtype_service as eventtype_service
import babyday.service.event_service as event_service
from babyday.data.events import Event

bp = Blueprint('event', __name__)

@bp.route('/eventlog', methods=['GET'])
def get_full_log():
    if 'user_id' not in session:
        return redirect(url_for('auth.login'))

    account_id = session['account_id']
    events:List[Event] = event_service.get_all_events(account_id)
    for event in events:
        print(event.person.firstname)
    return render_template('event/event_log.html', events = events)

babyday/templates/main/index.html
{% extends 'base.html' %}

{% block header %}
<nav>
  <ul class="horizontal">
    <li>New Event</li>
    <li><a href="{{url_for('event.get_full_log')}}"">View Log</a></li>
    <li><a href="#">Manage</a></li>
  </ul>
</nav>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="person">Person</label>
    <select name="person" id="person">
      {% for person in persons %}
      <option value="{{person.id}}">{{person.firstname}}</option>
      {% endfor %}
    </select>

    <label for="event">Event</label>
    <select name="event" id="event">
      {% for event_type in event_types %}
      <option value="{{event_type.id}}">{{event_type.name}}</option>
      {% endfor %}
    </select>
    <label for="event_time">Time</label>
    <input name="event_time" id="event_time" type="datetime-local">
    <label for="quantity">How much?</label>
    <input name="quantity" id="quantity">
    <label for="description">Notes</label>
    <input name="description" id="description">
    <input type="submit" value="Add Event">
  </form>
{% endblock %}